### ISSUE TITLE
Does this still work with electron-packager and electron-winstaller

### ISSUE THREAD

**Issue by drjasonharrison** [dustinblackman/mono-signtool#2]
I'm trying to use a modified version of your code but finding that the rebuilt signtool.exe does not ever see the called process exit. Even if I use /bin/echo as the command.
Suggestions?

**Comment by dustinblackman** [comment]
Need a bit more description here. This still works for me in projects using electron-winstaller, haven't had a problem.

**Comment by drjasonharrison** [comment]
Sorry for the lack of details, I thought that replacing signtool.exe with a modified version of your code would just work, but something is very wrong and I've spent the day chasing down logs and shell escapes and attempting to figure out why the modified signtool based on your mono-signtool main.go is not working. 

1. Machine setup: OSX 10.11.6 (El Capitan) with Node 7.8.0, npm 4.2.0, electron 1.6.4, electron-packager 8.7.0, electron-winstaller 2.5.2, wine-2.0.1, mono 4.8.0

2. Start with an electron build script, which you have already verified works without winstaller options certificateFile, certificatePassword, or signwithParams.

3. In main.go, replace line 39 with:
```
    "/usr/local/bin/mysigntool.sh", // Path for osslsigncode on OSX/Linux
```

4. Build signtool.exe and copy it into your node script's node_library/electron-winstaller/vendor
```
    make
    cp signtool.exe ../../NODESCRIPT/node_modules/electron-winstaller/vendor/signtool.exe
```

5. Create /usr/local/bin/mysigntool.sh with contents:
```
    #!/bin/bash
    # for mono-signtool mimic /usr/local/bin/osslsingtool 
    # by copying -in <filein> to -out <fileout> 
    set -euo pipefail
    echo `date` $@ >> /tmp/mysigntool.log
    while [[ $# -gt 1 ]]
    do
    	key="$1"
    
    	case $key in
    	    -in)
    	    FILE_IN="$2"
    	    shift # past argument
    	    ;;
    	    -out)
    	    FILE_OUT="$2"
    	    shift # past argument
    	    ;;
    	    *)
            # unknown option
    	    ;;
    	 esac
    	shift # past argument or value
    done
    
    echo  `date` FILE_IN  = "${FILE_IN}" >> /tmp/mysigntool.log
    echo  `date` FILE_OUT = "${FILE_OUT}">> /tmp/mysigntool.log
    cp "${FILE_IN}" "${FILE_OUT}"
    echo  `date` done >> /tmp/mysigntool.log
    exit 0
```

6. Make sure that mysigntool.sh is executable:
```
    chmod +x /usr/local/bin/mysigntool.sh 
```

7. Test mysigntool.sh:
```
    touch testFile
    /usr/local/bin/mysigntool.sh -in testFile -out testFile.signed
    ls testFile*
   cat /tmp/mysigntool.log
```

8. Test mysigntool.sh using wine at the command line; `pwd` is used here to provide the full path to the file
```
    wine cmd /c start /wait /unix /usr/local/bin/mysigntool.sh -in `pwd`/testFile -out `pwd`/testFile.signed /f keypath /p password
```
confirm that /tmp/mysigntool.log is written to.

9. Test signtool.exe calling mysigntool.sh:
```
    rm testfile.signed 
    wine cmd /c start /wait /unix `pwd`/node_modules/electron-winstaller/vendor/signtool.exe sign /a /f "/tmp/certificateFile" /p "password" `pwd`/testFile
```

wine will output to the shell:
```
    fixme:process:SetProcessPriorityBoost (0xffffffff,1): stub
    fixme:exec:SHELL_execute flags ignored: 0x00000100
```

A wine cmd window appears with only a flashing cursor, no progress is made. /tmp/mysigntool.log doesn't have any new entries. In another shell 
```
    touch testFile.signed
```

wine will output to the shell:
```
    fixme:exec:SHELL_execute flags ignored: 0x00000100
```

again, execute the command:
```
    touch testFile.signed
```

and the wine process will finally exit

- why does testFile.signed have to be created twice?
- why does /usr/local/bin/mysigntool.log not get called from signtool.exe?

**Comment by drjasonharrison** [comment]
Okay, I figured out why the two calls are required, looping over sha1 and sha256. Continuing my investigation.

**Comment by drjasonharrison** [comment]
I think I have it working again, the problem was trying to use cmd.Run() or time.Sleep() as both are affected by an optimization in go that triggers a bug in wine.

Go reads directly from windows shared memory, and wine does not update the system time in the memory: https://bugs.winehq.org/show_bug.cgi?id=38272

The wine issue affected a bunch of games, possibly because they also tried the same optimization, since 2011. https://bugs.winehq.org/show_bug.cgi?id=29168 (edited)
